# Generated by Django 6.0.5 on 2026-07-15 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cemetery', '0012_alter_cemetery_options_alter_exhumation_options_and_more'),
        ('finance', '0003_alter_paiement_mode_paiement'),
        ('reservations', '0003_reservation_cancelled_at_reservation_confirmed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alarm', models.CharField(choices=[('concession_expiration', 'Concession expirante'), ('payment_delay', 'Retard de paiement'), ('reservation_pending', 'Réservation en attente de validation'), ('exhumation_pending', 'Exhumation en attente de validation'), ('system_critical', 'Alerte système critique')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Résolue'), ('ignored', 'Ignorée')], default='active', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemetery.concession')),
                ('exhumation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cemetery.exhumation')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.facture')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alarme',
                'verbose_name_plural': 'Alarmes',
                'ordering': ['-created_at'],
            },
        ),
    ]
