# Generated by Django 6.0.5 on 2026-06-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemetery',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='grave',
            name='status',
            field=models.CharField(choices=[('free', 'Libre'), ('reserved', 'Réservé'), ('occupied', 'Occupé')], default='free', max_length=10),
        ),
    ]
