# Generated by Django 6.0.5 on 2026-06-13 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0002_alter_cemetery_name_alter_grave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grave',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='longitude',
        ),
        migrations.AddField(
            model_name='cemetery',
            name='total_area',
            field=models.FloatField(blank=True, help_text='Superficie en m²', null=True),
        ),
        migrations.AddField(
            model_name='grave',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='section',
            name='is_exploitable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='status',
            field=models.CharField(choices=[('free', 'Disponible'), ('reserved', 'Réservé'), ('occupied', 'Occupé'), ('unavailable', 'Non exploitable')], default='free', max_length=20),
        ),
    ]
