# Generated by Django 6.0.5 on 2026-06-13 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0003_remove_grave_latitude_remove_grave_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemetery',
            name='total_area',
            field=models.FloatField(blank=True, help_text='Superficie en m2', null=True),
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_concession', models.CharField(choices=[('temporaire', 'Temporaire'), ('perpetuelle', 'Perpétuelle')], default='temporaire', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='cemetery.grave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('status', models.CharField(choices=[('demandee', 'Demandée'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('effectuee', 'Effectuée')], default='demandee', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to=settings.AUTH_USER_MODEL)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='cemetery.grave')),
                ('validé_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
