# Generated by Django 6.0.5 on 2026-06-24 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0005_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhumation',
            old_name='validé_par',
            new_name='valide_par',
        ),
        migrations.AddField(
            model_name='cemetery',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='grave_length',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='grave_width',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='non_exploitable_area',
            field=models.FloatField(default=0, help_text='Zones non exploitables (routes, bâtiments, etc.)'),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='concession',
            name='document_autorisation',
            field=models.FileField(blank=True, null=True, upload_to='concessions/'),
        ),
        migrations.AddField(
            model_name='concession',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='date_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='document_pv',
            field=models.FileField(blank=True, null=True, upload_to='exhumations/'),
        ),
        migrations.AddField(
            model_name='grave',
            name='grave_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('familial', 'Familial'), ('vip', 'VIP')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='grave',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grave',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='grave',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='total_area',
            field=models.FloatField(blank=True, help_text='Superficie totale en m²', null=True),
        ),
    ]
