# Generated by Django 6.0.5 on 2026-06-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0007_alter_cemetery_non_exploitable_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cemetery',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='cemetery',
            name='city',
            field=models.CharField(default='Pointe-Noire', max_length=100),
        ),
        migrations.AddField(
            model_name='concession',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='date_exhumation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grave',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grave',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='grave_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('family', 'Familiale'), ('vip', 'VIP')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='grave',
            name='status',
            field=models.CharField(choices=[('free', 'Disponible'), ('reserved', 'Réservée'), ('occupied', 'Occupée'), ('unavailable', 'Indisponible')], default='free', max_length=20),
        ),
    ]
