# Generated by Django 6.0.5 on 2026-06-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0008_rename_location_cemetery_address_cemetery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemetery',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='document_pv',
            field=models.FileField(blank=True, null=True, upload_to='exhumations/pv/'),
        ),
    ]
