# Generated by Django 6.0.5 on 2026-06-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0009_alter_cemetery_city_alter_exhumation_document_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemetery',
            name='calculated_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grave',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grave',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
