# Generated by Django 6.0.5 on 2026-07-15 22:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0011_cemetery_updated_at_concession_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cemetery',
            options={'verbose_name': 'Cimetière', 'verbose_name_plural': 'Cimetières'},
        ),
        migrations.AlterModelOptions(
            name='exhumation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='grave',
            options={'ordering': ['code']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='cemetery_au_model_n_4f5db2_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='cemetery_au_timesta_93d8d5_idx',
        ),
        migrations.RenameField(
            model_name='exhumation',
            old_name='document_pv',
            new_name='pv_document',
        ),
        migrations.RenameField(
            model_name='exhumation',
            old_name='valide_par',
            new_name='validated_by',
        ),
        migrations.RenameField(
            model_name='grave',
            old_name='reserved_at',
            new_name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='cemetery',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='concession',
            name='document_autorisation',
        ),
        migrations.RemoveField(
            model_name='concession',
            name='renewal_count',
        ),
        migrations.RemoveField(
            model_name='concession',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exhumation',
            name='date_demande',
        ),
        migrations.RemoveField(
            model_name='exhumation',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='exhumation',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='grave',
            name='is_allocated',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('cemetery', 'name')},
        ),
        migrations.AddField(
            model_name='exhumation',
            name='autorisation_document',
            field=models.FileField(blank=True, null=True, upload_to='exhumations/autorisations/'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('status_change', 'Changement de statut'), ('login', 'Connexion'), ('payment', 'Paiement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Contour du cimetière', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='calculated_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='total_area',
            field=models.FloatField(default=0, help_text='Superficie totale en m²'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concession',
            name='grave',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concession', to='cemetery.grave'),
        ),
        migrations.AlterField(
            model_name='concession',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='concession',
            name='type_concession',
            field=models.CharField(choices=[('temporaire', 'Temporaire'), ('perpetuelle', 'Perpétuelle')], default='temporaire', max_length=20),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='date_exhumation',
            field=models.DateField(blank=True, help_text="Date réelle d'exhumation", null=True),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='date_prevue',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations_demandees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='motif_rejet',
            field=models.TextField(blank=True, default='', help_text='Motif si rejetée'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='observations',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('completed', 'Effectuée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='grave',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grave',
            name='grave_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grave',
            name='length',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='grave',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grave',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='grave',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible (Vert)'), ('reserved', 'Réservé (Orange)'), ('occupied', 'Occupé (Rouge)'), ('non_exploitable', 'Non exploitable (Gris)')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='grave',
            name='width',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='section',
            name='geometry',
        ),
    ]
