# Generated by Django 6.0.5 on 2026-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0012_alter_cemetery_options_alter_exhumation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cemetery',
            name='boundary',
        ),
        migrations.AddField(
            model_name='cemetery',
            name='largeur_totale',
            field=models.FloatField(default=100, help_text='Largeur totale du cimetière en mètres'),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude du centre du cimetière (ex: -4.7878)', null=True),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude du centre du cimetière (ex: 11.8750)', null=True),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='longueur_totale',
            field=models.FloatField(default=100, help_text='Longueur totale du cimetière en mètres'),
        ),
        migrations.AddField(
            model_name='concession',
            name='duree_annees',
            field=models.IntegerField(blank=True, help_text='Durée en années (uniquement pour concessions temporaires)', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='largeur',
            field=models.FloatField(default=20, help_text='Largeur de la section en mètres'),
        ),
        migrations.AddField(
            model_name='section',
            name='longueur',
            field=models.FloatField(default=50, help_text='Longueur de la section en mètres'),
        ),
        migrations.AddField(
            model_name='section',
            name='zone_non_exploitable',
            field=models.FloatField(default=0, help_text='Zone non exploitable dans cette section (m²)'),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='calculated_capacity',
            field=models.IntegerField(blank=True, help_text='Nombre théorique de places (calculé automatiquement)', null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='grave_length',
            field=models.FloatField(default=2.5, help_text="Longueur standard d'un caveau (m)"),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='grave_width',
            field=models.FloatField(default=1.2, help_text="Largeur standard d'un caveau (m)"),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='non_exploitable_area',
            field=models.FloatField(default=0, help_text='Zones non exploitables en m² (allées, espaces verts)'),
        ),
    ]
