# Generated by Django 6.0.5 on 2026-07-25 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0013_remove_cemetery_boundary_cemetery_largeur_totale_and_more'),
        ('reservations', '0004_alter_reservation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defunt_prenom', models.CharField(max_length=100, verbose_name='Prénom du défunt')),
                ('defunt_nom', models.CharField(max_length=100, verbose_name='Nom du défunt')),
                ('defunt_date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('defunt_date_deces', models.DateField(verbose_name='Date de décès')),
                ('date_inhumation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de l'inhumation")),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_inhumation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations_realisees', to=settings.AUTH_USER_MODEL, verbose_name="Agent ayant réalisé l'inhumation")),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations', to='cemetery.concession', verbose_name='Concession liée')),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inhumations', to='cemetery.grave', verbose_name='Caveau')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations', to='reservations.reservation', verbose_name="Réservation d'origine")),
            ],
            options={
                'verbose_name': 'Inhumation',
                'verbose_name_plural': 'Inhumations',
                'ordering': ['-date_inhumation'],
            },
        ),
        migrations.AddField(
            model_name='exhumation',
            name='inhumation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exhumations', to='cemetery.inhumation', verbose_name='Inhumation concernée'),
        ),
    ]
