# Generated by Django 6.0.5 on 2026-07-25 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0014_inhumation_exhumation_inhumation'),
        ('finance', '0004_alter_facture_options_alter_paiement_options_and_more'),
        ('reservations', '0004_alter_reservation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Concession', 'verbose_name_plural': 'Concessions'},
        ),
        migrations.AlterModelOptions(
            name='inhumation',
            options={'ordering': ['-date_inhumation'], 'verbose_name': 'Inhumation'},
        ),
        migrations.AddField(
            model_name='concession',
            name='contrat_document',
            field=models.FileField(blank=True, help_text='PDF du contrat signé', null=True, upload_to='concessions/contrats/'),
        ),
        migrations.AddField(
            model_name='concession',
            name='last_renewal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concession',
            name='renewed_count',
            field=models.IntegerField(default=0, help_text='Nombre de renouvellements'),
        ),
        migrations.AddField(
            model_name='concession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='calculated_capacity',
            field=models.IntegerField(blank=True, help_text='Nombre théorique de places', null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='grave_length',
            field=models.FloatField(default=2.5, help_text='Longueur standard caveau (m)'),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='grave_width',
            field=models.FloatField(default=1.2, help_text='Largeur standard caveau (m)'),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='largeur_totale',
            field=models.FloatField(default=100, help_text='Largeur totale (m)'),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude du centre du cimetière', null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude du centre du cimetière', null=True),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='longueur_totale',
            field=models.FloatField(default=100, help_text='Longueur totale (m)'),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='non_exploitable_area',
            field=models.FloatField(default=0, help_text='Zones non exploitables en m²'),
        ),
        migrations.AlterField(
            model_name='concession',
            name='duree_annees',
            field=models.IntegerField(blank=True, help_text='Durée en années (temporaire uniquement)', null=True),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='date_exhumation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='inhumation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exhumations', to='cemetery.inhumation'),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='motif_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grave',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('occupied', 'Occupé'), ('non_exploitable', 'Non exploitable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='agent_inhumation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations_realisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='concession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations', to='cemetery.concession'),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='date_inhumation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='defunt_date_deces',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='defunt_date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='defunt_nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='defunt_prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='grave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inhumations', to='cemetery.grave'),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inhumation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='section',
            name='largeur',
            field=models.FloatField(default=20, help_text='Largeur (m)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='longueur',
            field=models.FloatField(default=50, help_text='Longueur (m)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='zone_non_exploitable',
            field=models.FloatField(default=0, help_text='Zone non exploitable (m²)'),
        ),
        migrations.CreateModel(
            name='ConcessionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_date_fin', models.DateField()),
                ('nouvelle_date_fin', models.DateField()),
                ('duree_extension_annees', models.IntegerField()),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_renouvellement', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='cemetery.concession')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_renewals', to='finance.facture')),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_renewals_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renouvellement de concession',
                'ordering': ['-date_renouvellement'],
            },
        ),
    ]
