# Generated by Django 6.0.5 on 2026-07-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0015_alter_concession_options_alter_inhumation_options_and_more'),
        ('reservations', '0005_reservation_date_prevue_inhumation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhumation',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inhumation_record', to='reservations.reservation'),
        ),
    ]
