# Generated by Django 6.0.5 on 2026-07-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0016_alter_inhumation_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordre', 'name']},
        ),
        migrations.AddField(
            model_name='cemetery',
            name='espacement_caveaux',
            field=models.FloatField(default=0.5, help_text='Espacement entre les caveaux en mètres (pour circulation et entretien)'),
        ),
        migrations.AddField(
            model_name='section',
            name='capacite_caveaux',
            field=models.IntegerField(blank=True, help_text='Nombre de caveaux calculé automatiquement', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='ordre',
            field=models.IntegerField(default=0, help_text='Ordre de la section pour le nommage automatique'),
        ),
        migrations.AddField(
            model_name='section',
            name='polygon_coords',
            field=models.JSONField(blank=True, help_text='Coordonnées GPS du polygone de la section : [[lat1, lon1], [lat2, lon2], ...]', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='surface_calculee',
            field=models.FloatField(blank=True, help_text='Surface calculée automatiquement en m²', null=True),
        ),
        migrations.CreateModel(
            name='Allee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_allee', models.CharField(choices=[('principale', 'Principale'), ('secondaire', 'Secondaire'), ('sentier', 'Sentier')], default='secondaire', max_length=20)),
                ('largeur', models.FloatField(default=3.0, help_text="Largeur de l'allée en mètres")),
                ('coordinates', models.JSONField(help_text='Coordonnées GPS du tracé : [[lat1, lon1], [lat2, lon2], ...]')),
                ('surface_calculee', models.FloatField(blank=True, help_text="Surface de l'allée en m² (calculée automatiquement)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cemetery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allees', to='cemetery.cemetery')),
            ],
            options={
                'verbose_name': 'Allée',
                'verbose_name_plural': 'Allées',
                'ordering': ['type_allee', 'nom'],
            },
        ),
    ]
