# Generated by Django 6.0.5 on 2026-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemetery', '0017_alter_section_options_cemetery_espacement_caveaux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='status',
            field=models.CharField(choices=[('en_attente_creation', 'En attente de création'), ('active', 'Active'), ('expired', 'Expirée'), ('resiliee', 'Résiliée')], default='en_attente_creation', max_length=20),
        ),
        migrations.AlterField(
            model_name='concession',
            name='type_concession',
            field=models.CharField(choices=[('temporaire', 'Temporaire'), ('trentenaire', 'Trentenaire (30 ans)'), ('cinquantenaire', 'Cinquantenaire (50 ans)'), ('perpetuelle', 'Perpétuelle')], default='temporaire', max_length=20),
        ),
    ]
