# Generated by Django 6.0.5 on 2026-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_facture_is_paid_facture_paid_at_facture_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('mtn', 'MTN MoMo'), ('airtel', 'Airtel Money'), ('especes', 'Espèces'), ('virement', 'Virement')], max_length=20),
        ),
    ]
