# Generated by Django 6.0.5 on 2026-07-16 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_paiement_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_paye',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paiement',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement complet'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partielle', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Référence de transaction', max_length=100),
            preserve_default=False,
        ),
    ]
