# Generated by Django 6.0.5 on 2026-07-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_facture_options_alter_paiement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='valide', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Non payée'), ('partielle', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money')], max_length=20),
        ),
    ]
