# Generated by Django 6.0.5 on 2026-07-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_paiement_statut_validation_alter_facture_statut_and_more'),
        ('reservations', '0005_reservation_date_prevue_inhumation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='reservations.reservation'),
        ),
    ]
