# Generated by Django 6.0.5 on 2026-07-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_cancelled_at_reservation_confirmed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
    ]
