# Generated by Django 6.0.5 on 2026-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_prevue_inhumation',
            field=models.DateField(blank=True, null=True, verbose_name="Date prévue d'inhumation"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('inhumee', 'Inhumée')], default='pending', max_length=20),
        ),
    ]
