# Generated by Django 6.0.5 on 2026-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
