# Generated by Django 6.0.5 on 2026-06-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('nouvelle_reservation', 'Nouvelle réservation'), ('retard_paiement', 'Retard de paiement'), ('concession_expirante', 'Concession expirante'), ('reservation_validee', 'Réservation validée'), ('reservation_annulee', 'Réservation annulée'), ('facture_payee', 'Facture payée'), ('exhumation_validee', 'Exhumation validée')], max_length=50),
        ),
    ]
