# Generated by Django 6.0.5 on 2026-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_system_notification_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('nouvelle_reservation', 'Nouvelle réservation'), ('retard_paiement', 'Retard de paiement'), ('concession_expirante', 'Concession expirante'), ('reservation_validee', 'Réservation validée'), ('reservation_annulee', 'Réservation annulée'), ('facture_payee', 'Facture payée'), ('exhumation_validee', 'Exhumation validée'), ('concession_creee', 'Concession créée'), ('concession_expiree', 'Concession expirée'), ('inhumation_confirmee', 'Inhumation confirmée'), ('signalement_caveau', 'Signalement de caveau')], max_length=50),
        ),
    ]
